services:
  redis:
    image: redis:8.2.3-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - gitdash_network

  postgres:
    image: postgres:18-alpine3.22
    container_name: postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword123
      POSTGRES_DB: gitdashdb
    volumes:
      #- ./.docker/database:/var/lib/postgresql/data
      - ./packages/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - gitdash_network

  backend:
    image: gitdash-backend:1.0.0
    build:
      context: packages/backend/
      dockerfile: GitDashBackend/Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=gitdashdb;Username=exampleuser;Password=examplepassword123
      - Redis__Configuration=redis:6379
      - FrontendOrigin=http://localhost:8080
    ports:
      - "5053:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - gitdash_network

  frontend:
    image: gitdash-frontend:1.0.0
    build:
      context: packages/frontend/GitDash
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:5053
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - gitdash_network

networks:
  gitdash_network:
    driver: bridge
